### ISSUE TITLE
Incomplete betacode conversion

### ISSUE THREAD

**Issue by cmil** [dracor-org/greekdracor#3]
The body of [sophocles-ichneuthae](https://github.com/dracor-org/greekdracor/blob/master/tei/sophocles-ichneutae.xml) partly still contains beta code that hasn't been properly transformed into Greek characters. This is probably because the text of this play is highly fragmented.

See for instance https://github.com/dracor-org/greekdracor/blob/fea2036ccfd37abfb3e1adcaa9ba34195e40767c/tei/sophocles-ichneutae.xml#L153

For more instances in other files see [below](https://github.com/dracor-org/greekdracor/issues/3#issuecomment-492777811).

**Comment by nevmenandr** [comment]
Fixed

**Comment by cmil** [comment]
There are still some instances of unconverted passages and incompletely converted accents in Ichneutae, e.g.

https://github.com/dracor-org/greekdracor/blob/5d63392932f56ee7f2eea4de182baa8378da0f94/tei/sophocles-ichneutae.xml#L429 or https://github.com/dracor-org/greekdracor/blob/5d63392932f56ee7f2eea4de182baa8378da0f94/tei/sophocles-ichneutae.xml#L657

In addition, at least the following documents have unconverted passages as well:

- [ ] tei/aristophanes-ecclesiazusae.xml
- [ ] tei/aristophanes-knights.xml
- [ ] tei/aristophanes-birds.xml
- [ ] tei/sophocles-ichneutae.xml
- [ ] tei/aristophanes-clouds.xml
- [ ] tei/euripides-ion.xml

I found those by grepping for the backslash character, which seems to be frequently unrecognised as an accent. There may be other instances where the conversion did not go well. We should carefully check the other documents too.

**Comment by nevmenandr** [comment]
Fixed
