### ISSUE TITLE
Chorus (Χορός) should be <personGrp> instead of <person>

### ISSUE THREAD

**Issue by cmil** [dracor-org/greekdracor#4]

**Comment by nevmenandr** [comment]
And what about the cases like Αἰσχύλος καί Εὐριπίδης (in "Frogs")? The same?

**Comment by nevmenandr** [comment]
done

**Comment by cmil** [comment]
Aischylos and Euripides are two separate characters with individual IDs. They should be referenced individually like this:

```xml
<sp who="#aisxulos #euripidhs">
  <speaker>Αἰσχύλος καί Εὐριπίδης</speaker>
  ...
</sp>
```

The `@who` attribute can contain multiple references separated by white space.

**Comment by cmil** [comment]
And one more thing: in order to be consistent with the other corpora the name of a `<personGrp>` should be wrapped in a `<name>` element, not `<persName>`. Sorry, I should have provided a proper description of the issue.

**Comment by nevmenandr** [comment]
Done

**Comment by cmil** [comment]
Very good, thanks, @nevmenandr!
