### ISSUE TITLE
Change IDs from Betacode gibberish to actual transliteration

### ISSUE THREAD

**Issue by lehkost** [dracor-org/greekdracor#5]
This seems to be a leftover of the Betacode encoding:

```xml
<person xml:id="klutaimhstra">
  <persName>Κλυταιμήστρα</persName>
</person>

**Comment by lehkost** [comment]
The proposed way to transliterate is without diacritics, so the above example would transfrom to ```klytaimestra```.

**Comment by nevmenandr** [comment]
Done
