### ISSUE TITLE
Add textClass/classCode

### ISSUE THREAD

**Issue by cmil** [dracor-org/greekdracor#9]
In order to make genre information available via the API the appropriate Wikidata IDs should be added via the `textClass/classCode` elements. So far GreekDraCor seems to provide `textClass/keywords` only.

**Comment by lehkost** [comment]
Closed via https://github.com/dracor-org/greekdracor/commit/e45aca31769215a6bb555d890ed191af832e77a9.

There's also a new genre encoded (Sophocles' *Ichneutae*):
```xml
<textClass>
  <keywords>
    <term type="genreTitle">Satyr play</term>
  </keywords>
  <classCode scheme="http://www.wikidata.org/entity/">Q1050848</classCode>
</textClass>
```

**Comment by cmil** [comment]
@lehkost Should we then add "Satyr play" to the text classes recognised by DraCor in  https://github.com/dracor-org/dracor-api/blob/82ac6e34994ab2830ed41651dfcbc3673d9d6e5a/modules/config.xqm#L72-L81?

**Comment by lehkost** [comment]
Yes, I'd suggest that.

**Comment by cmil** [comment]
@lehkost done
